dist: trusty
sudo: false
language: c

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
        key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - sourceline: "ppa:avsm/ppa"
    packages:
      - build-essential
      - ocaml
      - ocaml-native-compilers
      - camlp4-extra
      - opam
      - llvm-4.0
      - llvm-4.0-dev
      - libllvm-4.0-ocaml-dev

before_script:
  - |
    if [ ! -d "$HOME/.cmake/bin" ]
    then wget "https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz" &&
    tar xzf cmake-3.8.0.tar.gz &&
    cd cmake-3.8.0/ &&
    ./bootstrap --parallel=3 --prefix=$HOME/.cmake -- -DCMAKE_USE_OPENSSL=false &&
    make -j3 &&
    make install
    fi

  - opam init -a
  - opam install -y llvm ounit

script:
  - cd $TRAVIS_BUILD_DIR/ocaml
  - make test
  - ./run_tests.native

cache:
  directories:
    - $HOME/.cmake

env:
  - PATH=$HOME/.cmake/bin:$PATH
